language: c

sudo: false

addons:
  apt:
    packages:
    - python-pygments
    - fonts-inconsolata # doesn't seem to be dependended on by texlive-fonts-extra?
    - texlive
    - texlive-luatex
    - texlive-latex-extra # for xstring, among others
    - texlive-generic-extra # for iftex, among others
    - texlive-fonts-extra # for libertine, among others
    - wget
    - curl
    - sed
    - grep

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: deploy
  on:
    branch: master

script: make LATEX_EXTRA_FLAGS="-interaction=nonstopmode"

after_success:
  - mkdir -p deploy/nightly
  - cp -f rewriting/rewriting.pdf cover.pdf abstract.pdf rewriting-with-cover.pdf deploy/nightly/
